server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://219.245.18.46/netease
    username: netease
    password: netease2017!@#
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
